### ISSUE TITLE
Doesn't work with string representations of timestamps

### ISSUE THREAD

**Issue by manolodd** [patrickknabe/node-red-contrib-ui-clock#1]
Hi,

thank you for this node. It's great!!

However it doesn't work fine when the input is a string representation of a timestamp (what is usual when receiving a timestamp through MQTT, for instance). Including a parseInt() of the payload would work fine with "1614715781000" and also with 1614715781000.

In this line:

const date = new Date( +payload || 0 );

Kindest regards

**Comment by patrickknabe** [comment]
Hi,

I am very pleased that you like the watch. I will check why strings are not taken as payload. Maybe there will be a new version soon.

Many greetings
Patrick

**Comment by patrickknabe** [comment]
Hi,

just checked the behaviour. But I cannot find any bug? As expected does the plus-sign, in the line you mentioned, the casting to int. So any string-input is converted to int and is usable as a valid timestamp. What system do you have (Linux, Windows) and what version of node.js and Node-RED are you using?

Many greetings
Patrick
