### ISSUE TITLE
No dots showing around the clock

### ISSUE THREAD

**Issue by GeoffNT** [patrickknabe/node-red-contrib-ui-clock#3]
I've just installed this but only get the hands of the clock showing and no blue dots for the number positions as shown on the example. Also all 3 hands are white on mine whereas the example has a blue second hand. I guess this is to do with my dashboard palette settings but I really don't want to change that, is there anywhere I can adjust the colours of the individual clock components for just this node?

Thanks

**Comment by patrickknabe** [comment]
Hi, the clock uses the dashboard color settings. During the next months I will give the opportunity to adjust the colors in the settings of the clock. At the moment it cannot be changed... sorry!
